# Generated by Django 3.1.4 on 2021-05-18 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_bids_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
